name: CI/CD Pipeline for Calculadora

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/inmobiliaria:v1 .
          docker push ${{ secrets.DOCKER_USER }}/inmobiliaria:v1

      - name: Deplor yaml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./compose.yml"
          target: ~/deploy/

      - name: Deploy with Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deploy
            sudo chmod 666 /var/run/docker.sock
            docker compose down || true
            docker compose pull
            docker compose up -d